[theme]
base = "dark"
primaryColor = "#00D1B2"                  # Helles Türkis/Grün (wie Bayernwerk)
backgroundColor = "#121824"               # Dunkles Anthrazit/Blau-Schwarz
secondaryBackgroundColor = "#1E2738"      # Etwas helleres Dunkelgrau für Karten/Boxen
textColor = "#FFFFFF"                     # Reinweiße Schrift
font = "sans serif"

[client]
toolbarMode = "minimal"
